### PR TITLE
Pull request for WAZO-3180-update-for-bullseye-2

### PR DESCRIPTION
**Pull request by fblackburn1**

### CODE REVIEW

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
regate

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by jfbourque** [comment]
recheck

**Pull request closed without merging**
